inekf_node:
  ros__parameters:
    frame_id: "odom"
    child_frame_id: "base_link"
    imu_topic: "/olivecam/filtered_ahrs_synced"
    
    velocity_topic: "/imu/velocity_synced"
    
    noise:
      gyro_bias: 1e-4
      accel_bias: 1e-2
      
      
      
      
      
      
      
      
      
# ===============FOR LATER==================
